[package]
name = "hub_chain_trigger"
edition = "2024"

[features]
debug = []

[lib]
crate-type = ['cdylib']

[dependencies]
iroha_crypto = { git = "https://github.com/hyperledger-iroha/iroha.git", rev = "a84bc8893451cf08f346eb476097c13ca7bf65fb", default-features = false }
iroha_trigger = { git = "https://github.com/hyperledger-iroha/iroha.git", rev = "a84bc8893451cf08f346eb476097c13ca7bf65fb" }

anyhow = { version = "1.0", default-features = false }
dlmalloc = { version = "0.2.6", features = ["global"] }
panic-halt = "0.2.0"
serde = { version = "1.0.219", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0.143", default-features = false }
